--Crea la tabla
CREATE TABLE IF NOT EXISTS ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROMATRICULA INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL
);

--Insertar registros
INSERT INTO ODONTOLOGOS(NUMEROMATRICULA, NOMBRE, APELLIDO) VALUES(543232, 'Mark', 'Jackson');
INSERT INTO ODONTOLOGOS(NUMEROMATRICULA, NOMBRE, APELLIDO) VALUES(342523, 'Tomás', 'Alejandro');